# Generated by Django 3.2.9 on 2023-02-17 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulk', models.TextField(verbose_name='主体内容')),
                ('type', models.CharField(max_length=32, verbose_name='活动类型')),
                ('timeStamp', models.CharField(max_length=32, verbose_name='时间戳-创建时间')),
                ('theme', models.CharField(max_length=32, verbose_name='活动主题')),
                ('pic', models.CharField(blank=True, max_length=256, null=True, verbose_name='图片')),
                ('cover', models.CharField(blank=True, max_length=256, null=True, verbose_name='封面')),
            ],
        ),
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sch_No', models.CharField(max_length=32, verbose_name='组织编码')),
                ('orgType', models.CharField(max_length=16, verbose_name='组织类型')),
                ('orgName', models.CharField(max_length=64, verbose_name='组织名称')),
                ('profile', models.CharField(default='空', max_length=32, verbose_name='头像')),
                ('orgIntro', models.TextField(blank=True, default='在这里介绍组织', null=True, verbose_name='组织简介')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulk', models.TextField(default='该政策是：', verbose_name='主体')),
                ('policyType', models.CharField(max_length=16, verbose_name='政策类型')),
                ('timeStamp', models.CharField(max_length=32, verbose_name='时间戳-创建时间')),
                ('source', models.CharField(max_length=64, verbose_name='来源')),
                ('webLink', models.CharField(max_length=256, verbose_name='网页链接')),
                ('cover', models.CharField(blank=True, max_length=256, null=True, verbose_name='封面')),
                ('pic', models.CharField(blank=True, max_length=256, null=True, verbose_name='图片')),
                ('theme', models.CharField(max_length=32, verbose_name='主题')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=32, verbose_name='主题')),
                ('bulk', models.TextField(verbose_name='主体内容')),
                ('pic', models.CharField(blank=True, max_length=256, null=True, verbose_name='图片')),
                ('timeStamp', models.CharField(max_length=32, verbose_name='时间戳-创建时间')),
                ('thumb', models.IntegerField(default=0, verbose_name='点赞量')),
            ],
        ),
        migrations.CreateModel(
            name='Soldier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='姓名')),
                ('nick', models.CharField(max_length=32, verbose_name='昵称')),
                ('profile', models.CharField(default='空', max_length=32, verbose_name='头像')),
                ('sch_No', models.CharField(max_length=10, verbose_name='学号')),
                ('gender', models.CharField(max_length=16, verbose_name='性别')),
                ('insit', models.CharField(max_length=16, verbose_name='书院')),
                ('selfIntro', models.TextField(blank=True, default='在这里介绍自己', null=True, verbose_name='个人简介')),
                ('phoneNo', models.CharField(max_length=11, verbose_name='手机号')),
                ('qqNo', models.CharField(blank=True, max_length=10, null=True, verbose_name='QQ号码')),
                ('wechatNo', models.CharField(blank=True, max_length=64, null=True, verbose_name='微信id')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('type', models.CharField(default='军人', max_length=16, verbose_name='类型')),
            ],
        ),
        migrations.CreateModel(
            name='StuInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='姓名')),
                ('nick', models.CharField(max_length=32, verbose_name='昵称')),
                ('profile', models.CharField(default='空', max_length=32, verbose_name='头像')),
                ('sch_No', models.CharField(max_length=10, verbose_name='学号')),
                ('gender', models.CharField(max_length=16, verbose_name='性别')),
                ('insit', models.CharField(max_length=16, verbose_name='书院')),
                ('selfIntro', models.TextField(blank=True, default='在这里介绍自己', null=True, verbose_name='个人简介')),
                ('phoneNo', models.CharField(max_length=11, verbose_name='手机号')),
                ('qqNo', models.CharField(blank=True, max_length=10, null=True, verbose_name='QQ号码')),
                ('wechatNo', models.CharField(blank=True, max_length=64, null=True, verbose_name='微信id')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('type', models.CharField(default='学生', max_length=16, verbose_name='类型')),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='名字')),
                ('insit', models.CharField(max_length=16, verbose_name='书院')),
                ('contact', models.CharField(max_length=32, verbose_name='联系方式')),
                ('subject', models.CharField(max_length=16, verbose_name='主体')),
                ('major', models.CharField(max_length=16, verbose_name='专业')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulk', models.TextField(verbose_name='主体内容')),
                ('timeStamp', models.CharField(max_length=32, verbose_name='时间戳-创建时间')),
                ('pic', models.CharField(blank=True, max_length=256, null=True, verbose_name='图片')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='stu.post')),
                ('schNo_soldier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='stu.soldier')),
                ('schNo_stu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='stu.stuinfo')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='schNo_soldier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stu.soldier'),
        ),
        migrations.AddField(
            model_name='post',
            name='schNo_stu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stu.stuinfo'),
        ),
    ]
