# Generated by Django 3.2.9 on 2023-02-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='schNo_soldier',
        ),
        migrations.RemoveField(
            model_name='post',
            name='schNo_stu',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='schNo_soldier',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='schNo_stu',
        ),
        migrations.AddField(
            model_name='post',
            name='schNo',
            field=models.CharField(default=0, max_length=16, verbose_name='学号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reply',
            name='schNo',
            field=models.CharField(default=1, max_length=16, verbose_name='学号'),
            preserve_default=False,
        ),
    ]
