# Generated by Django 3.2.9 on 2023-02-17 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0002_auto_20230217_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuinfo',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='stu', verbose_name='用户头像'),
        ),
    ]
