# Generated by Django 3.2.9 on 2023-02-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0003_alter_stuinfo_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='act', verbose_name='封面'),
        ),
        migrations.AlterField(
            model_name='act',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='act', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='org',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='org', verbose_name='用户头像'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='policy', verbose_name='封面'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='policy', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='post', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='reply', verbose_name='用户头像'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='soldier', verbose_name='用户头像'),
        ),
        migrations.AlterField(
            model_name='stuinfo',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='norstu', verbose_name='用户头像'),
        ),
    ]
