# Generated by Django 3.2.9 on 2023-02-21 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0004_auto_20230218_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='cover',
            field=models.CharField(default=12, max_length=100, verbose_name='封面'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='act',
            name='pic',
            field=models.CharField(default=12, max_length=100, verbose_name='图片'),
            preserve_default=False,
        ),
    ]
