# Generated by Django 3.2.9 on 2023-02-21 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0005_auto_20230221_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='cover',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='封面'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='pic',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='图片'),
        ),
    ]
