# Generated by Django 3.2.9 on 2023-02-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0006_auto_20230221_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='profile',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='用户头像'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pic',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='用户头像'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='profile',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='用户头像'),
        ),
        migrations.AlterField(
            model_name='stuinfo',
            name='profile',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='用户头像'),
        ),
    ]
