# Generated by Django 3.2.9 on 2023-02-23 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0007_auto_20230222_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='pic',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='用户头像'),
        ),
    ]
