# Generated by Django 4.1.5 on 2023-02-26 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0008_alter_reply_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='cover',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='封面'),
        ),
        migrations.AlterField(
            model_name='act',
            name='pic',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='act',
            name='theme',
            field=models.CharField(max_length=256, verbose_name='活动主题'),
        ),
        migrations.AlterField(
            model_name='org',
            name='profile',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='用户头像'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='cover',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='封面'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='pic',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='theme',
            field=models.CharField(max_length=256, verbose_name='主题'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pic',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='post',
            name='theme',
            field=models.CharField(max_length=256, verbose_name='主题'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='pic',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='用户头像'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='profile',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='用户头像'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='wechatNo',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='微信id'),
        ),
        migrations.AlterField(
            model_name='stuinfo',
            name='profile',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='用户头像'),
        ),
        migrations.AlterField(
            model_name='stuinfo',
            name='wechatNo',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='微信id'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='contact',
            field=models.CharField(max_length=64, verbose_name='联系方式'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='major',
            field=models.CharField(max_length=64, verbose_name='专业'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='subject',
            field=models.CharField(max_length=64, verbose_name='学科'),
        ),
    ]
